version: '3.8'

services:
  # 1. バックエンドサービス (todo-server)
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: backend-server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    volumes:
      # ローカルのsrcフォルダをコンテナの/app/srcにマウント
      - ./server/src:/app/src

  # 2. フロントエンドサービス (todo-client)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: frontend-client
    restart: always
    ports:
      - "5173:80"
    depends_on:
      - server
    volumes:
      # ローカルのsrcフォルダをコンテナの/app/srcにマウント
      - ./client/src:/app/src

  # 3. データベースサービス (MongoDB)
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    # MongoDBの管理者ユーザーを環境変数で設定
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: