services:
  # 1. バックエンドサービス (todo-server)
  server:
    build: ./server
    container_name: backend-server
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env
    depends_on:
      - mongo
    volumes:
      - ./todo-server/src:/app/src
    

  # 2. フロントエンドサービス (todo-client)
  client:
    build: ./client
    container_name: frontend-client
    restart: always
    ports:
      - "5173:4173"  # ← Vite preview のデフォルトポートは 4173
    depends_on:
      - server
  

  # 3. データベースサービス (MongoDB)
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    # MongoDBの管理者ユーザーを環境変数で設定
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    tty: true

volumes:
  mongo-data: